//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyVersion("2.1.1.0")]
[assembly: AssemblyFileVersion("2.1.0.0")]
[assembly: AssemblyConfiguration("Release")]


